export const ADD_ITEM_TO_WISHLIST = 'itemList/ADD_ITEM_TO_WISHLIST';
export const ADD_ITEM_TO_WISHLIST_SUCCESS =
  'itemList/ADD_ITEM_TO_WISHLIST_SUCCESS';
export const ADD_ITEM_TO_WISHLIST_ERROR = 'itemList/ADD_ITEM_TO_WISHLIST_ERROR';
export const GET_MORE_ITEMS = 'itemList/GET_MORE_ITEMS';
export const GET_MORE_ITEMS_SUCCESS = 'itemList/GET_MORE_ITEMS_SUCCESS';
export const GET_MORE_ITEMS_ERROR = 'itemList/GET_MORE_ITEMS_ERROR';
export const SEARCH_ITEMS = 'itemList/SEARCH_ITEMS';
export const SEARCH_ITEMS_SUCCESS = 'itemList/SEARCH_ITEMS_SUCCESS';
export const SEARCH_ITEMS_ERROR = 'itemList/SEARCH_ITEMS_ERROR';
